# Generated by Django 2.2.2 on 2020-03-19 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID of the actor object')),
                ('actor_text', models.CharField(blank=True, max_length=255, null=True)),
                ('verb', models.CharField(max_length=100, verbose_name='Verb of the action')),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID of the target object')),
                ('target_text', models.CharField(blank=True, max_length=255, null=True)),
                ('nf_type', models.CharField(default='default', max_length=20, verbose_name='Type of notification')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False, verbose_name='Read status')),
                ('deleted', models.BooleanField(default=False, verbose_name='Soft delete status')),
                ('actor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor', to='contenttypes.ContentType', verbose_name='Content type of actor object')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Notification receiver')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_target', to='contenttypes.ContentType', verbose_name='Content type of target object')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
