// SKELETON
export const SKELETONLOADING = "SKELETONLOADING";

// AUTH
export const LOADING = "LOADING";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const PASSWORD_VALIDATION = "PASSWORD_VALIDATION";

//hierarchy
export const GET_LINE_MANAGER = "GET_LINE_MANAGER";

// TEMPLETE
export const GET_TEMPLETE_LIST = "GET_TEMPLETE_LIST";
export const GET_TEMPLETE = "GET_TEMPLETE";
// PAGE TRANSITION
export const PAGE_LOAD = "PAGE_LOAD";
export const PAGE_LOADED = "PAGE_LOADED";
export const SPLASH_LOAD = "SPLASH_LOAD";

// PROFILE
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_DASH_PANEL_DATA = "GET_DASH_PANEL_DATA";
export const GET_ROLES = "GET_ROLES";

// GROUP
export const GET_GROUP_DETAILS = "GET_GROUP_DETAILS";
export const GET_TYPE_GROUPS = "GET_TYPE_GROUPS";

// PROJECTS, TASKS & GROUPS
export const GET_TYPE_PROJECTS = "GET_TYPE_PROJECTS";
export const GET_GROUP_PROJECTS = "GET_GROUP_PROJECTS";

export const GET_PROJECT_DETAIL = "GET_PROJECT_DETAIL";
export const GET_TYPE_TASKS = "GET_TYPE_TASKS";
export const GET_TYPE_TASKS_OVERVIEW = "GET_TYPE_TASKS_OVERVIEW";
export const GET_TASK_DETAIL = "GET_TASK_DETAIL";
export const GET_TYPE_ISSUES = "GET_TYPE_ISSUES";
export const GET_ISSUE_DETAIL = "GET_ISSUE_DETAIL";
export const GET_ADMIN_PROJECTS = "GET_ADMIN_PROJECTS";
export const GET_PROJECT_CHART = "GET_PROJECT_CHART"
export const TASK_SUBMIT_DONE = "TASK_SUBMIT_DONE";

// MEMBERS
export const GET_TYPE_MEMBERS = "GET_TYPE_MEMBERS";

// KPI
export const GET_USER_AVG_KPI = "GET_USER_AVG_KPI";
export const GET_KPI_DETAILS = "GET_KPI_DETAILS";
export const GET_EMPLOYEE_YEAR_KPI = "GET_EMPLOYEE_YEAR_KPI";

// ALERT

export const ALERT_MESSAGE = "ALERT_MESSAGE";
export const ERROR_MESSAGE = "ERROR_MESSAGE";

// ACCOUNTS

export const PAYSLIP_AUTH = "PAYSLIP_AUTH";
export const PAYSLIP_GET = "PAYSLIP_GET";
export const PAYSLIP_AUTH_ERROR = "PAYSLIP_AUTH_ERROR";
export const PAYSLIP_NOT_GEN = "PAYSLIP_NOT_GEN";

export const GET_ALL_GROSS = "GET_ALL_GROSS";
export const GET_USER_GROSS_HISTORY = "GET_USER_GROSS_HISTORY";
export const UPDATE_GROSS = "UPDATE_GROSS";
export const GET_SERVICE = "GET_SERVICE";
export const GET_PAYROLL_USER = "GET_PAYROLL_USER";
export const CREATE_NEW_SERVICE = "CREATE_NEW_SERVICE";
export const GET_EMP_INFO = "GET_EMP_INFO";
export const SUBSCRIBE_USER = "SUBSCRIBE_USER";
export const GET_YEAR = "GET_YEAR";
export const GET_ALL_PROVIDENT_USERS = "GET_ALL_PROVIDENT_USERS";
export const GET_ALL_PROVIDENT_USER = "GET_ALL_PROVIDENT_USER";
export const GET_SAL_DIST = "GET_SAL_DIST";
export const GET_ALL_PAYSLIPS = "GET_ALL_PAYSLIPS";
export const GET_ALLSALARY_PAYSLIPS = "GET_ALLSALARY_PAYSLIPS";
export const USER_PROVIDENT_FUND = "USER_PROVIDENT_FUND";
export const PROVIDENT_FUND_REQUESTS = "PROVIDENT_FUND_REQUESTS";
export const GET_MONTHLY_DEDUCTIONS = "GET_MONTHLY_DEDUCTIONS";
export const GET_PAYROLL_USER_PROFILE = "GET_PAYROLL_USER_PROFILE";
export const GET_USER_LOANS = "GET_USER_LOANS";
export const GET_LOAN = "GET_LOAN";
export const GET_ALL_LOANS = "GET_ALL_LOANS";
export const GET_USERPAYABLE_LOANS = "GET_USERPAYABLE_LOANS";

export const GET_REQUESTS = "GET_REQUESTS";
export const GET_ALL_REQUESTS = "GET_ALL_REQUESTS";
// SEARCH DB
export const GET_SEARCH_RESULT = "GET_SEARCH_RESULT";

// Modal
export const DELETE_MODAL_SUBMIT_DONE = "DELETE_MODAL_SUBMIT_DONE";
export const MODAL_DELETE_COMPLETE = "MODAL_DELETE_COMPLETE";

// OTP CODE
export const ACCESS_VALIDITY = "ACCESS_VALIDITY";
export const GET_PAYROLL_PAYSLIP = "GET_PAYROLL_PAYSLIP";
//ERROR
export const ERROR_401 = "ERROR_401";
export const ERROR_408 = "ERROR_408";
export const ERROR_FORBIDDEN = "ERROR_FORBIDDEN";
// NEWS
export const GET_TYPE_NEWS = "GET_TYPE_NEWS";
export const RESET_NEWS = "RESET_NEWS";

// NOTICE
export const GET_TYPE_NOTICE = "GET_TYPE_NOTICE";
export const GET_NOTICE_DETAILS = "GET_NOTICE_DETAILS";

// HR
export const GET_DESIGNATIONS = "GET_DESIGNATIONS";

// NOTIFICATIONS
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";

// CHAT
export const GET_ALL_CONTACTS = "GET_ALL_CONTACTS";
export const GET_THREADS = "GET_THREADS";
export const GET_THREAD_MESSAGES = "GET_THREAD_MESSAGES";
export const RESET_THREAD_MESSAGE = "RESET_THREAD_MESSAGE";

//ATTENDENCE
export const GET_GROUP_ATTENDANCE = "GET_GROUP_ATTENDANCE";
export const GET_USER_ATTENDANCE = "GET_USER_ATTENDANCE";
export const GET_USER_NAME = "GET_USER_NAME";
export const GET_ALL_GROUPS = "GET_ALL_GROUPS";
export const LOADING_ATTENDANCE = "LOADING_ATTENDANCE";
export const LOADING_SCROLL = "LOADING_SCROLL";
export const LOADING_COMPLETED = "LOADING_COMPLETED";
export const CLEAR_USER_ATTENDANCE = "CLEAR_USER_ATTENDANCE";
export const RESET_INFINITY_SCROLL = "RESET_INFINITY_SCROLL";
export const INFINITY_SCROLL = "INFINITY_SCROLL";

// Fetch data for Inbox
export const GET_INBOX_DATA_NEXT = "GET_INBOX_DATA_NEXT";
export const GET_INBOX_DATA_PREV = "GET_INBOX_DATA_PREV";
export const GET_SENT_DATA_NEXT = "GET_SENT_DATA_NEXT";
export const GET_SENT_DATA_PREV = "GET_SENT_DATA_PREV";
export const LOADING_INBOX_DATA = "LOADING_INBOX_DATA";
export const REPORT_SENT_SUCCESS = "REPORT_SENT_SUCCESS";
export const LOADING_COMPLETED_INBOX_DATA = "LOADING_COMPLETED_INBOX_DATA";
export const RESET_INBOX_DATA = "RESET_INBOX_DATA";
// HOLIDAYS
export const GET_HOLIDAY_DATA = "GET_HOLIDAY_DATA";

//WEEKLY REPORT
export const GET_WEEKLY_REPORT = "GET_WEEKLY_REPORT";

// Fetch Working Hour Config Data
export const GET_ATTENDANCE_CONFIG = "GET_ATTENDANCE_CONFIG";
export const GET_ALL_DAYS = "GET_ALL_DAYS";
export const UPDATE_ATTENDANCE_CONFIG = "UPDATE_ATTENDANCE_CONFIG";

// FORM
// export const FORM_SUBMIT_COMPLETE = "FORM_SUBMIT_COMPLETE";

// Summmary Report
export const GET_SUMMARY_LIST = "GET_SUMMARY_LIST";
