# Generated by Django 2.2.2 on 2021-07-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uspl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='started_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='prerequisite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='wbs_number',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
