# Generated by Django 2.2.2 on 2021-07-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uspl', '0003_remove_task_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='most_likely_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='optimistic_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='pessimistic_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
