# Generated by Django 2.2.2 on 2021-07-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uspl', '0004_auto_20210726_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='most_likely_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='optimistic_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='pessimistic_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
