# Generated by Django 2.2.2 on 2021-07-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uspl', '0005_auto_20210726_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='wbs_number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
