# Generated by Django 2.2.2 on 2021-07-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uspl', '0006_auto_20210726_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prerequisite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='wbs_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
