# Generated by Django 2.2.2 on 2020-03-19 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(blank=True, max_length=20, null=True)),
                ('week', models.CharField(blank=True, max_length=20, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('month', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('cc_list', models.ManyToManyField(blank=True, related_name='cc_list', to=settings.AUTH_USER_MODEL)),
                ('recipent', models.ManyToManyField(related_name='recipent_list', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('body', models.CharField(blank=True, max_length=2000, null=True)),
                ('read', models.BooleanField(default=False)),
                ('recipent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_recipent', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_sender', to=settings.AUTH_USER_MODEL)),
                ('workstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weekly_status.WorkStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('workstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_status.WorkStatus')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityNextWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('workstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_status.WorkStatus')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityInProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.CharField(blank=True, max_length=1000, null=True)),
                ('next', models.CharField(blank=True, max_length=1000, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('workstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_status.WorkStatus')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('workstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_status.WorkStatus')),
            ],
        ),
    ]
